/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unsafe_Driver */

#ifndef _Included_unsafe_Driver
#define _Included_unsafe_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     unsafe_Driver
 * Method:    compileInMemory0
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Lunsafe/NativeModule;
 */
JNIEXPORT jobject JNICALL Java_unsafe_Driver_compileInMemory0
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

/*
 * Class:     unsafe_Driver
 * Method:    invoke
 * Signature: (Lunsafe/NativeFunction;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_unsafe_Driver_invoke
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     unsafe_Driver
 * Method:    getFunctions
 * Signature: (Lunsafe/NativeModule;)[Lunsafe/NativeFunction;
 */
JNIEXPORT jobjectArray JNICALL Java_unsafe_Driver_getFunctions
  (JNIEnv *, jclass, jobject);

/*
 * Class:     unsafe_Driver
 * Method:    delete
 * Signature: (Lunsafe/NativeModule;)V
 */
JNIEXPORT void JNICALL Java_unsafe_Driver_delete
  (JNIEnv *, jclass, jobject);

/*
 * Class:     unsafe_Driver
 * Method:    initializeNativeCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_unsafe_Driver_initializeNativeCode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
